name: mulitple jobs in single workflow 
on: push
jobs:
  Singleworfklflow:
    runs-on: ubuntu-latest
    steps:
      - name: Learning Multiple Job in Single workflow
        run: |
          echo "This is First Job"
  Build:
    runs-on: ubuntu-latest
    needs: Singleworfklflow
    steps:
      - name: Build Testing
        run: 
          echo "welcome Build"