name: Learning to Pass Artifcats among Job 

on:
  workflow_dispatch:
jobs:
  uploading-artifcat:
  runs-on: ubuntu-latest
    steps:
      - run: echo "Hello Amal and Jyoti" >> sample.txt
      - uses: actions/uploading-artifcat@v2
        with:
          name: Learning
          path: sample.txt
  dowloading-artifcat:
  runs-on: ubuntu-latest
  needs: uploading-artifcat
    steps:
      - uses: actions/download-artifcat@v2
        with:
          name: Learning
      - run : cat sample.txt
        
