name: checking version for posgreqsq
on:
  push:
    branches:
      - main
      - 'features/**'
jobs:
  version:
    runs-on: ubuntu-latest
    steps:
    - name: running postgreq sql
      run: |
        sudo systemctl start postgresql
        echo "$(psql --version)"
