name: Learning special filie in Github worflow GITHUB_OUTPUT
on:
  push:
    branches:
      - main
      - 'feature/**'
jobs:
  sample:
    runs-on: ubuntu-latest
    steps:
      - name: sample
        run: | 
          echo "learning new variable GITHUB_OUTPUT"
          echo "tag=v1.0.0" >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT