name: practice gha
on: workflow_dispatch
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: hello world
        run: |
          echo "welcome to github actions"
          echo "welcome Jyoti"
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Build_1
        run: echo " welcome to Build"
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Test_1
        run: echo "welcome to test"
  
