
name: learning workflow input
on:
  workflow_dispatch:
    inputs:
      environment:
        description: This is for Giving Input at workflow_dispatch
        required: true
        type: choice
        options:
          - dev
          - Production
          - testing
jobs:
  workflowiput:
    runs-on: ubuntu-latest
    steps:
      - name: This is for input from user at workflow end
        run: |
          echo "Deploy at ${{inputs.environment}}"
